
services:
  # 1. The Database Service (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: bookmark_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookmark_manager
    ports:
      - "5434:5432"   # Maps Docker port 5434 to local dev environment port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data, no data lose on restart

  # 2. The Admin Panel (PG Admin) -
  pgadmin:
    image: dpage/pgadmin4
    container_name: bookmark_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"   # access established on http://localhost:5050
    depends_on:
      - postgres

volumes:
  postgres_data:    # Named volume for database persistence